In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import preprocessing

BACA DATASET PENYAKIT JANTUNG 


In [2]:
df = pd.read_csv('jantungdataset.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

MENENTUKAN DATA TRAIN

In [5]:
X = df.iloc[:, 0:13]
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

MENENTUKAN DATA TEST

In [9]:
y = df.iloc[:, -1]
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

SET DATA TRAIN DAN TEST 

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

MODEL RANDOM FOREST

In [19]:
from sklearn.ensemble import RandomForestRegressor
  
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
  
regressor.fit(X_train, y_train)  

RandomForestRegressor(random_state=0)

In [20]:
Y_pred = regressor.predict(X_test)

HASIL AKURASI

In [24]:
acc = accuracy_score(y_test, Y_pred.round())
print("Hasil akurasi dari model Random Forest")
acc

Hasil akurasi dari model Random Forest


1.0

CONFUSION MATRIX RANDOM FOREST

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test.values,Y_pred.round())
cm

array([[ 97,   0],
       [  0, 108]], dtype=int64)

CLASSIFICATION REPORT RANDOM FOREST


In [29]:
cls_report = classification_report(y_test, Y_pred.round())
print(f'Laporan Classification:\n{cls_report}')

Laporan Classification:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00       108

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



MODEL NAIVE BAYES

In [30]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
score = metrics.accuracy_score(y_test, y_pred.round())
print("Hasil akurasi dari model Naive Bayes")
score


Hasil akurasi dari model Naive Bayes


0.8048780487804879

CONFUSION MATRIX NAIVE BAYES

In [32]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test.values,y_pred.round())
cm2

array([[74, 23],
       [17, 91]], dtype=int64)

CLASSIFICATION REPORT NAIVE BAYES

In [33]:
cls_report = classification_report(y_test, y_pred.round())
print(f'Laporan Classification:\n{cls_report}')

Laporan Classification:
              precision    recall  f1-score   support

           0       0.81      0.76      0.79        97
           1       0.80      0.84      0.82       108

    accuracy                           0.80       205
   macro avg       0.81      0.80      0.80       205
weighted avg       0.81      0.80      0.80       205



MODEL DECISION TREE

In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
dt = DecisionTreeClassifier(max_depth=None, min_samples_split = 2)
dt.fit(X_train, y_train)
y_predd = dt.predict(X_test)
scores2 = metrics.accuracy_score(y_test, y_predd)
print("Hasil akurasi dari model Decision Tree")
scores2


Hasil akurasi dari model Decision Tree


1.0

CONFUSION MATRIX DECISION TREE

In [39]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test.values,y_predd.round())
cm3

array([[ 97,   0],
       [  0, 108]], dtype=int64)

CLASSIFICATION REPORT NAIVE BAYES

In [40]:
cls_report = classification_report(y_test, y_predd.round())
print(f'Laporan Classification:\n{cls_report}')

Laporan Classification:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00       108

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

